<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>infinitescroll.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>jquery.uploadfile.min.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>customs/init.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>customs/pretty.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/holder.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/ink.min.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/ink-ui.min.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/autoload.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/jquery.autosize.min.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/blocksit.min.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/jquery.timers-1.2.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>customs/dropDownStyle.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>libs/jquery.oembed.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>jquery.tokeninput.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>jquery.dropdown.js"></script>
<script type="text/javascript" src="<?php echo $this->f3->get('JS'); ?>customs/general.js"></script>